# This workflow will build the stripes bundle and deploy to S3. 

name: bundle-deploy
on: 
  workflow_dispatch:

jobs: 
  bundle-deploy:
    env:
      FOLIO_NPM_REGISTRY: 'https://repository.folio.org/repository/npm-folioci'
      NODEJS_VERSION: '18'
      #STRIPES_TRANSPILE_TOKENS: '@indexdata'
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name:  Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ env.NODEJS_VERSION }}
          check-latest: true
          always-auth: true
 
      - name: Set yarn config for FOLIO modules
        run: yarn config set @folio:registry $FOLIO_NPM_REGISTRY

      - name: List FOLIO modules 
        run: yarn list --pattern @folio
      
      #- name: Run yarn lint
      #  run: yarn lint
      #  continue-on-error: true

      - name: Build Stripes bundle
        run: yarn build

      - name: Deploy Stripes bundle to S3
        run: yarn deploy output
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FOLIO_DEV_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FOLIO_DEV_S3_DEV_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
